version: '2'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.1
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Path(`/foo`) || PathPrefix(`/foo/`)"
      #- "traefik.http.middlewares.my-add-prefix.addprefix.prefix=/xyz"
      #- "traefik.http.routers.whoami.middlewares=my-add-prefix@docker"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/foo,/fiibar"
      - "traefik.http.routers.whoami.middlewares=test-stripprefix@docker"
  blanket:
    image: luphord/blanketdb:0.4.0
    labels:
      - "traefik.http.routers.blanket.rule=Path(`/db`) || PathPrefix(`/db/`)"
      - "traefik.http.middlewares.strip-db.stripprefix.prefixes=/db"
      - "traefik.http.routers.blanket.middlewares=strip-db@docker"
  fossil:
    image: duvel/fossil:2.10
    entrypoint: /usr/bin/fossil server --repolist --user admin /opt/fossil --baseurl http://localhost/fossil
    volumes:
      - /tmp/mytest:/opt/fossil
    labels:
      - "traefik.http.routers.fossil.rule=Path(`/fossil`) || PathPrefix(`/fossil/`)"
      - "traefik.http.middlewares.strip-fossil.stripprefix.prefixes=/fossil"
      - "traefik.http.routers.fossil.middlewares=strip-fossil@docker"
  metime:
    build: ./metime
    labels:
      - "traefik.http.routers.metime.rule=Path(`/metime`) || PathPrefix(`/metime/`)"
      - "traefik.http.middlewares.strip-metime.stripprefix.prefixes=/metime"
      - "traefik.http.routers.metime.middlewares=strip-metime@docker"